
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:tacoloco
    username: sa
    password: password
    driverClassName: org.h2.Driver
  application:
    name: tacoloco

  jpa:
    hibernate:
      ddl-auto: none
  #  database-platform: org.hibernate.dialect.H2Dialect

server:
  servlet:
    context-path: /tacoloco
